core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    # books
    path('book', views.book_list, name="book_list"),
    path('book/create/', views.book_create, name="book_create"),
    path('book/<int:pk>', views.book_detail, name="book_detail"),
    path('book/<int:pk>/update', views.book_update, name="book_update"),
    path('book/<int:pk>/delete', views.book_delete, name="book_delete"),

    # membership
    path('member', views.member_list, name="member_list"),
    path('member/create', views.member_create, name="member_create"),
    path('member/<int:pk>', views.member_detail, name="member_detail"),

    # borrow a book
    path('member/<int:pk>/borrow', views.book_borrow, name="book_borrow"),

    # notification
    path('notification', views.notification, name="notification"),

    # profile
    path('profile', views.profile, name="profile"),
    path('profile/members', views.profile_member, name="profile_member"),
    path('profile/books', views.profile_book, name="profile_book"),
    path('profile/delete', views.profile_library_delete, name="profile_delete"),
    path('profile/change_password', views.profile_password_change, name="profile_password_change"),

]

workbench/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('account.urls', namespace='account')),

    path('book', include('core.urls', namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models
from datetime import datetime
from account.models import Library

# Create your models here.


class Membership(models.Model):
    library_name = models.ForeignKey(Library, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    email = models.EmailField()
    phone_number = models.CharField(max_length=50)
    home_address = models.CharField(max_length=2000)
    date_joined = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.name


# including books
class Book(models.Model):
    library_name = models.ForeignKey(Library, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    author = models.CharField(max_length=200)
    location = models.CharField(max_length=500)
    quantity = models.PositiveIntegerField(default=0)
    cover = models.ImageField()

    def __str__(self):
        return self.title


class BookAmount(models.Model):
    book = models.ForeignKey(Book, related_name="quantity_serial", on_delete=models.CASCADE)
    serial_number = models.CharField(max_length=50)

    def __str__(self):
        return self.serial_number


# Borrowing books
class BorrowedBook(models.Model):
    book = models.ForeignKey(Book, related_name="borrowed_book", on_delete=models.CASCADE)
    book_serial = models.ForeignKey(BookAmount, related_name="borrowed_book_serial", on_delete=models.CASCADE)
    borrowed_by = models.ForeignKey(Membership, related_name="borrowed_book_name", on_delete=models.CASCADE)
    date_borrowed = models.DateTimeField(default=datetime.now)
    date_to_be_returned = models.DateField(null=True, blank=True)


class Notification(models.Model):
    library_name = models.ForeignKey(Library, related_name="notification", on_delete=models.CASCADE)
    heading = models.CharField(max_length=250)
    message = models.CharField(max_length=5000)

    date_created = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.account.username

core/forms.py
from django import forms
from .models import Book, Membership, BorrowedBook


class BookCreationForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = (
            "title",
            "author",
            "location",
            "quantity",
            "cover",
        )

class MembershipCreationForm(forms.ModelForm):
    class Meta:
        model = Membership
        fields = (
            "name",
            "email",
            "phone_number",
            "home_address",
        )

class BookBorrowingForm(forms.ModelForm):
    class Meta:
        model = BorrowedBook
        fields = {
            "book",
        }

core/views.py
from django.shortcuts import render, redirect
from .models import Book, BookAmount, BorrowedBook, Membership, Notification
from .forms import BookCreationForm, MembershipCreationForm, BookBorrowingForm
from .serial_num_generator import auto_generate
from django.contrib import messages
from account.models import Library, User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login

# Create your views here.

'''members management'''
@login_required
def member_list(request):
    member = Membership.objects.all()
    return render(request, "core/member-list.html", {"member": member})


def member_create(request):
    current_user = request.user
    if Library.objects.filter(owner=current_user):
        library = Library.objects.get(owner=current_user)

    form = MembershipCreationForm()
    if request.method == "POST":
        form = MembershipCreationForm(request.POST, request.FILES)
        if form.is_valid():
            name = form.cleaned_data["name"]
            email = form.cleaned_data["email"]
            number = form.cleaned_data["phone_number"]
            address = form.cleaned_data["home_address"]

            new_member = Membership.objects.create(library_name=library, name=name, email=email, phone_number=number, home_address=address)
            new_member.save()

            notification_heading = "Membership Creation"
            notification_message = f"Membership for {email} created successfully"
            alert = Notification.objects.create(library_name=library, heading=notification_heading, message=notification_message)
            alert.save()

            messages.success(request, "Member added successfully")
            return redirect("core:member_list")
        else:
            messages.info(request, "There is a problem in your form!")
            return redirect("core:member_create")

    return render(request, "core/member-create.html", {"form": form})


def member_detail(request, pk):
    current_user = request.user
    if Library.objects.filter(owner=current_user):
        library = Library.objects.get(owner=current_user)

    member = Membership.objects.get(id=pk)

    book = []
    if member.borrowed_book_name.exists():
        borrowed_book = member.borrowed_book_name.all()
        
        for item in borrowed_book:
            book.append(item)

            if request.method == "POST":    
                if request.POST.get("returnBook"):
                    item.delete()

                    notification_heading = "Book Returning"
                    notification_message = f"{member.name} with email ({member.email}) returned a '{item.book.title}' book, with serial number: {item.book_serial.serial_number}"
                    alert = Notification.objects.create(library_name=library, heading=notification_heading, message=notification_message)
                    alert.save()

                    messages.info(request, 'Book has being returned')
                    return redirect("core:member_detail", member.id)

    if request.method == "POST":
        if request.POST.get("remove"):
            member.delete()

            messages.success(request, "Membership terminated successfully")
            return redirect("core:member_list")

    return render(request, "core/member-detail.html", {"member": member, "book": book})


def book_borrow(request, pk):
    current_user = request.user
    if Library.objects.filter(owner=current_user):
        library = Library.objects.get(owner=current_user)

    book = Book.objects.all()
    member = Membership.objects.get(id=pk)
    form = BookBorrowingForm()

    if request.method == "POST":
        form = BookBorrowingForm(request.POST)
        if form.is_valid():
            book_name = form.cleaned_data["book"]
            return_date = request.POST["return_date"]
            serial_num = request.POST["serial_num"]            

            if Book.objects.filter(title=book_name).exists():
                the_book = Book.objects.get(title=book_name)

                if BookAmount.objects.filter(serial_number=serial_num):
                    the_book_copy = BookAmount.objects.get(serial_number=serial_num)

                    if the_book == the_book_copy.book:
                        if BorrowedBook.objects.filter(book_serial=the_book_copy.id).exists():
                            
                            messages.info(request, "Book with that serial number has been borrowed")
                            return redirect("core:book_borrow", member.id)
                        else:
                            borrow_book = BorrowedBook.objects.create(book=book_name, book_serial=the_book_copy, 
                                                                        borrowed_by=member, date_to_be_returned=return_date)

                            borrow_book.save()

                            notification_heading = "Book Borrowing"
                            notification_message = f"{member.email} borrowed '{book_name}' with serial number '{the_book_copy}'"
                            alert = Notification.objects.create(library_name=library, heading=notification_heading, message=notification_message)
                            alert.save()

                            messages.success(request, "Book borrowed successfully")
                            return redirect("core:member_detail", member.id)
                    else:
                        messages.info(request, "Book doesn't have such serial number")
                        return redirect("core:book_borrow", member.id)
                else:
                    messages.info(request, "Serial number doesn't exists")
                    return redirect("core:book_borrow", member.id)

    else:
        return render(request, "core/book-borrow.html", {"book": book,
                                                    "member": member,
                                                    "form": form})


'''book management'''
@login_required
def book_list(request):
    book = Book.objects.all()
    return render(request, "core/book-list.html", {"book": book})


def book_create(request):
    current_user = request.user
    if Library.objects.filter(owner=current_user):
        library = Library.objects.get(owner=current_user)

    form = BookCreationForm()
    if request.method == "POST":
        form = BookCreationForm(request.POST, request.FILES)

        if form.is_valid():
            title = form.cleaned_data['title']
            author = form.cleaned_data['author']
            location = form.cleaned_data['location']
            quantity = form.cleaned_data['quantity']
            image = form.cleaned_data['cover']

            new_book = Book.objects.create(library_name=library, title=title, author=author, location=location, quantity=quantity, cover=image)
            new_book.save()
            
            # To create many books as possible
            amount = 0
            if amount < quantity:
                while amount < quantity:
                    amount += 1
                    serial = auto_generate(n=10)
                    book = BookAmount.objects.create(book=new_book, serial_number=serial)
                    book.save()

                notification_heading = "Book Creation"
                notification_message = f"Uploaded '{title}' book with {quantity} copies"
                alert = Notification.objects.create(library_name=library, heading=notification_heading, message=notification_message)
                alert.save()

                messages.info(request, "Book added Successfully!")
                return redirect("core:book_list")
            else:
                new_book.delete()
                messages.info(request, "Book quantity field error")
                return redirect("core:book_create")
        else:
            messages.info(request, "Form is not valid!")
            return redirect("core:book_create")
    else:
        return render(request, "core/book-create.html", {"form": form})


def book_detail(request, pk):
    book_item = Book.objects.get(id=pk)
    book_amount = book_item.quantity_serial.all()

    borrowed_book_amount = 0
    
    books = [] # "books" is for borrowed books

    for item in book_amount:
        if BorrowedBook.objects.filter(book_serial=item).exists():
            borrowed_book_amount += 1
            books.append(item)

    optional = 0
    # the purpose of using optional is to check whether a book has being borrowed
    # therefore it can't be deleted or updated
    for book in book_amount: 
        while book.borrowed_book_serial.exists():
            optional += 1
            break
        else:
            pass
      
    return render(request, "core/book-detail.html", {"book_item": book_item,
                                                    "books_borrowed": books,
                                                    "borrowed_book_amount": borrowed_book_amount,
                                                    "book_amount": book_amount,
                                                    "books": books,
                                                    "optional": optional})


def book_update(request, pk):
    current_user = request.user
    if Library.objects.filter(owner=current_user):
        library = Library.objects.get(owner=current_user)

    book = Book.objects.get(id=pk)
    book_amount =  book.quantity_serial.all()
    book_form = BookCreationForm(instance=book)

    optional = 0
    # the purpose of using optional is to check whether a book has being borrowed
    # therfore it can't be updated
    for item in book_amount: 
        while item.borrowed_book_serial.exists():
            optional += 1
            break
        else:
            pass
    
    book_amount_list = []

    if book_amount:
        for item in book_amount:
            book_amount_list.append(item)
    
    if request.method == "POST":

core/templates/core/book-borrow.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<style type="text/css">
    .alert{
        height: 40px;
        width: 50%;
        display: flex;
        justify-content: center;
    }
    .alert svg{
        width: 20px;
    }
    .text{
        margin-left: 10px;
    }
    .borrow-book{
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    .borrow-book form{
        flex-direction: column;
        align-items: center;
    }
    .borrow-book input{
        width: 300px;
    }
</style>


<h1>Borrow a book</h1>
    <hr>


<div class="borrow-book">
    {% for message in messages %}
        <div class="alert alert-danger d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <div class="text">
                {{ message }}
            </div>
        </div>
    {% endfor %}





    <form action="", method="post">
        {% csrf_token %}

        <h3>Member: {{ member.name }}</h3>
        <hr>

        {{ form | crispy }}

        <br>
        
        Return Date
        <br>
        <input type="date" name="return_date" class="textinput textInput form-control">

        <br>
        Serial Number
        <input type="text" name="serial_num" class="textinput textInput form-control">
        <br>

        <input type="submit", value="Borrow" class="btn btn-success" >
        <br><br>
        <a href="{% url 'core:member_detail' member.id %}"><input type="button" value="Go back" class="btn btn-primary"></a>

    </form>
</div>

{% endblock content %}

core/templates/core/book-create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <style type="text/css">
        .alert{
            height: 40px;
        }
        .alert svg{
            width: 20px;
        }
        .alert svg{
            margin-left: 40%;
        }
        .text{
            margin-left: 10px;
        }
    </style>

    <div class="col-12">
        <br> <h2>Upload a new book</h2> <hr>

        {% for message in messages %}
        <div class="alert alert-danger d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <div class="text">
                {{ message }}
            </div>
        </div>
        {% endfor %}


        <form method="post", enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}
            <br>
            <div class="d-grid gap-2">
                <input class="btn btn-primary" type="submit", value="Upload">
            </div>
        </form>

    </div>

{% endblock content %}

core/templates/core/book-delete.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
    .delete-btn button{
        margin-right: 20px;
    }
    .alert{
        height: 40px;
    }
    .alert svg{
        width: 20px;
    }
    .alert svg{
        margin-left: 28%;
    }
    .text{
        margin-left: 10px;
    }
</style>

<div class="delete-confirmation">
    {% if optional > 0 %}
        <h2>Deleting "{{ book.title }}" will also remove all copies</h2>
        <hr>
        
        <div class="alert alert-danger d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <div class="text">
                A copy of this book has being borrowed so it can't be deleted
            </div>
        </div>
    {% else %}
        <h2>Deleting "{{ book.title }}" will also remove all copies</h2>
        <hr>

        <form method="post">
            {% csrf_token %}
            
            <div class="delete-btn">
                <button class="btn btn-success", name="confirmDelete", value="confirmDelete">Confirm</button>
                <a href="{% url 'core:book_detail' book.id %}"><input type="button" class="btn btn-danger", value="Decline"></a>
            </div>    
        </form>
    {% endif %}
</div>

{% endblock content %}

core/templates/core/book-detail.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
    .book-detail{
        display: flex;
        margin-top: 10px;
    }
    .book-quantity{
        margin-left: 10%;
    }
    .serial-heading{
        font-size: 30px;
    }
    .book-quantity-list li{
        font-size: 20px;
        list-style: none;
    }
</style>


<br>
<h1 class="">Book: {{ book_item.title }}</h1>
<hr>


<div class="book-detail">
   


    <div class="card mb-3" style="height: 10%;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{{ book_item.cover.url }}" class="img-fluid rounded-start" width="400">
            </div>

            <div class="col-md-8">

                <div class="card-body">

                    <h3 class="card-title text-muted">Author: {{ book_item.author }}</h3><hr>
                    <h4 class="card-text text-muted">Location: {{ book_item.location }}</h4><br>

                    <h3 class="card-text"><small class="text-muted">Total Quantity: {{ book_item.quantity }}</small></h3>
                    <h3 class="card-text"><small class="text-muted">Borrowed: {{ borrowed_book_amount }}</small></h3>

                    <div class="d-grid gap-3 d-md-flex justify-content-md-end">

                        {% if optional > 0 %}
                            <button class="btn btn-secondary me-md-2" type="button">Update</button>
                            <button class="btn btn-secondary" type="button">Delete</button>
                        {% else %}
                            <a href="{% url 'core:book_update' book_item.id %}"><button class="btn btn-primary me-md-2" type="button">Update</button></a>

                            <a href="{% url 'core:book_delete' book_item.id %}"><button class="btn btn-danger" type="button">Delete</button></a>
                        {% endif %}

                    </div>

                </div>
            </div>
        </div>
    </div>


    <!-- To get all the book serial numbers available -->
    <div class="book-quantity">
        <div class="card" style="width: 18rem;">
            <div class="card-header">
                Book Serial Numbers
            </div>
            <!-- To get borrowed books or not -->
            {% for book in book_amount %}
                <ul class="list-group list-group-flush">
                    {% if book in books %}
                        <li class="list-group-item">Book: {{ book.serial_number }} ( borrowed )</li>
                    {% else %}
                        <li class="list-group-item">Book: {{ book.serial_number }} ( available )</li>
                    {% endif %}
                </ul>
            {% endfor %}
        </div>
    </div>
   
</div>


{% endblock %}

core/templates/core/book-list.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
    .alert{
        height: 40px;
    }
    .alert svg{
        width: 20px;
    }
    .alert svg{
        margin-left: 40%;
    }
    .text{
        margin-left: 10px;
    }
</style>



    <h1>List of books</h1>
    <hr><br><br>

    {% for message in messages %}
        <div class="alert alert-success d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
            <div class="text">
                {{ message }}
            </div>
        </div>
    {% endfor %}

    <div class="create-btn">
        <a href="{% url 'core:book_create' %}">
            <div class="d-grid gap-2">
                <button class="btn btn-primary">
                    Create a new book
                </button>
            </div>
        </a>
    </div>

    <div class="row row-cols-1 row-cols-md-5 g-4">
        {% for book in book %}

            {% if book.library_name.owner == request.user %}

                <a href="{% url 'core:book_detail' book.id %}", style="text-decoration: none; color: black;">
                    <div class="col">
                        <div class="card h-100" style="width: 200px;">
                            <img src="{{ book.cover.url }}", class="card-img-top" alt="..." height="250px" width="200px">
                            
                            <div class="card-body">
                                <h5 class="card-title">{{ book.title }}</h5>
                                <p class="card-text">Location: {{ book.location }}</p>
                            </div>

                            <!-- <div class="card-footer">
                                <small class="text-muted">last borrowed: </small>
                            </div> -->
                        </div>
                    </div>
                </a>
                
            {% endif %}

        {% endfor %}
    </div>

{% endblock content %}

core/templates/core/book-update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<style type="text/css">
    .alert{
        height: 40px;
    }
    .alert svg{
        width: 20px;
    }

    {% if optional > 0 %}
        .alert svg{
            margin-left: 28%;
        }
    {% else %}
        .alert svg{
            margin-left: 40%;
        }
    {% endif %}
    
    .text{
        margin-left: 10px;
    }
</style>

<div class="col-12">
    <br>
    <h2>Update Book</h2>
    <hr>

    {% if optional > 0 %}
    <div class="alert alert-danger d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <div class="text">
            A copy of this book has being borrowed so it can't be updated
        </div>
    </div>
    {% else %}
        {% for message in messages %}
            <div class="alert alert-danger d-flex align-items-center" role="alert">
                <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                <div class="text">
                    {{ message }}
                </div>
            </div>
        {% endfor %}


        <form method="post", enctype="multipart/form-data">
            {% csrf_token %}
            {{ book_form | crispy }}
            <br>

            <div class="copies">
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault" name="keep_changes">
                    <label class="form-check-label" for="flexSwitchCheckDefault">Do you want to keep these copies?</label>
                </div>
                <hr>

                <ul>    
                    {% for book_amount in book_amount_list %}
                        <li>Book: {{ book_amount }}</li>
                    {% endfor %}
                </ul>
            </div>

            <hr>
            <div class="d-grid gap-2">
                <input class="btn btn-primary" type="submit", value="Upload", name="done">
            </div>
        </form>
    {% endif %}
</div>

{% endblock content %}

core/templates/core/member-create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<style type="text/css">
    .alert{
        height: 40px;
    }
    .alert svg{
        width: 20px;
    }
    .alert svg{
        margin-left: 40%;
    }
    .text{
        margin-left: 10px;
    }
</style>

<div class="col-12">
    <br> <h2>Add a new member</h2> <hr>

    {% for message in messages %}
        <div class="alert alert-danger d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <div class="text">
                {{ message }}
            </div>
        </div>
    {% endfor %}

    <form method="post", enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <br>
        
        <div class="d-grid gap-2">
            <input type="submit", value="Create", class="btn btn-success">
        </div>
    </form>

</div>



{% endblock content %}

core/templates/core/member-detail.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
    .alert{
        height: 40px;
        width: 50%;
        display: flex;
        justify-content: center;
    }
    .alert svg{
        width: 20px;
    }
    .text{
        margin-left: 10px;
    }
    .borrowed-book{
        position: relative;
        /* border: 1px solid black; */
        top: 20px
    }
    .borrowed-book button{
        position: relative;
        /* margin-top: 10px; */
        margin-left: 26px;
    }
    .borrowed-book li{
        /* border: 1px solid black; */
        margin-top: 10px;
    }
    .member{
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    .action-buttons{
        display: flex;
    }
    .action-buttons input{
        margin-left: 20px;
    }
</style>


<hr>


    {% for message in messages %}
        <div class="alert alert-success d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
            <div class="text">
                {{ message }}
            </div>
        </div>
    {% endfor %}


<div class="member">
    <h2 class="display-5">Member: {{ member.name }}</h2>
    <br>


    <h4>Email: {{ member.email }}</h4>
    <h4>Number: {{ member.phone_number }}</h4>
    <h4>Address: {{ member.home_address }}</h4>
    <h4>Registration Date: {{ member.date_joined }}</h4>
    <hr>

    <div class="action-buttons">
        <a href="{% url 'core:book_borrow' member.id %}"><button class="btn btn-primary">Borrow a Book</button></a>

        {% if member.borrowed_book_name.exists %}
            <input type="button", value="Remove member" class="btn btn-secondary">
        {% else %}
            <form method="post">
                {% csrf_token %}
                <input type="submit", value="Remove member" class="btn btn-success" name="remove">
            </form>
        {% endif %}
    </div>


    <!-- list of borrowed books -->
    <div class="borrowed-book">
        <div class="card" style="width: 30rem;">
            <div class="card-header">
                Borrowed Books
            </div>
            <ul>
                <form method="post" class="borrow-form">
                    {% csrf_token %}

                    {% for book in book %}
                        <li>{{ book.book }}: {{ book.book_serial }}
                            <button class="btn btn-primary btn-sm", name="returnBook", value="returnBook">
                                Return Book
                            </button>
                        </li>
                    {% endfor %}
                </form>
            </ul>
        </div>
    </div>

    <hr>



</div>

{% endblock content %}

core/templates/core/member-list.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">

    .create-btn{
        top: 20%;
        margin-bottom: 20px;
    }
    .create-btn a{
        text-decoration: none;
    }
    h1{
        padding-bottom: -5%;
    }
    .member a{
        text-decoration: none;
        color: black;
        position: relative;
    }
    .member a::after{
        content: '';
        width: 0;
        height: 3px;
        position: absolute;
        bottom: -5px;
        left: 50%;
        transform: translateX(-50%);
        background: green;
        transition: width 0.3s;
    }
    .member a:hover::after{
        width: 100px;
    }
    .alert{
        height: 40px;
    }
    .alert svg{
        width: 20px;
    }
    .alert svg{
        margin-left: 40%;
    }
    .text{
        margin-left: 10px;
    }
</style>

<h1>Membership List</h1>
<hr>


{% for message in messages %}
    <div class="alert alert-success d-flex align-items-center" role="alert">
    <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
    <div class="text">
        {{ message }}   
    </div>
  </div>
{% endfor %}


<div class="create-btn">
    <a href="{% url 'core:member_create' %}">
        <div class="d-grid gap-2">
            <button class="btn btn-success">
                Add a Person
            </button>
        </div>
    </a>
</div>

<table class="table table-hover">

    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone Number</th>
        <th>Address</th>
        <th>Borrowed Books</th>
    </tr>

    {% for member in member %}
        {% if member.library_name.owner == request.user %}
            <tr> 
                <td class="member"><a href="{% url 'core:member_detail' member.id %}">{{ member.name }}</a></td>
                <td>{{ member.email }}</td>
                <td>{{ member.phone_number}}</td>
                <td>{{ member.home_address }}</td>

                {% if member.borrowed_book_name.exists %}
                    <td>Yes</td>
                {% else %}
                    <td>No</td>
                {% endif %} 
            </tr>
        {% endif %}
    {% endfor %}
</table>


{% endblock content %}